#!/usr/bin/env python3
"""
generate_paper_tables.py — PART 4: IEEE-Access-ready LaTeX tables.
==================================================================

Emits five LaTeX tables that compile directly inside an IEEE Access manuscript with no manual
editing. Every cell is read from an EXECUTED artifact at generation time; nothing is hardcoded.

    paper_tables/table_combined_ablation.tex       configurations x measured metrics
    paper_tables/table_statistics.tex              per-configuration statistics (CI, effect size, p)
    paper_tables/table_interactions.tex            expected vs observed interaction effects
    paper_tables/table_threshold_sensitivity.tex   conclusion stability under +/-20% thresholds
    paper_tables/table_cross_dataset.tex           the ablation replicated on every real dataset

REQUIRED PREAMBLE (IEEE Access / IEEEtran):
    \\usepackage{booktabs}
    \\usepackage{multirow}     % only if you enable grouped dataset rows
Each table is wrapped in table* (double-column float) because the metric matrices are wide.

NOTE ON A PRE-EXISTING FILENAME COLLISION (reported, not silently resolved):
`paper_tables/table_combined_ablation.{md,csv}` already exist in the repository and are produced by
`paper_table_generator.py` — despite the name they contain a PER-STAGE LATENCY table, not an
ablation (a known misnomer in the repo). This generator writes only the `.tex`, so those tracked
files are never overwritten. The `.tex` here is the REAL combined ablation.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

from e5b_metric_note import NOTE_TEX

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "paper_tables"
CA = ROOT / "experiments" / "combined_ablation"


CHECK = r"\checkmark"
CROSS = r"$\times$"


def yn(v):
    return CHECK if v else CROSS


def L(rel):
    p = ROOT / rel
    return json.loads(p.read_text()) if p.exists() else {}


def esc(s) -> str:
    """Escape a value for LaTeX so the tables COMPILE (underscores in config names are the usual
    culprit; en-dashes and arrows from the JSON also need care)."""
    if s is None:
        return "--"
    if isinstance(s, bool):
        return r"\checkmark" if s else "--"
    if isinstance(s, float):
        return f"{s:.3f}"
    s = str(s)
    s = (s.replace("\\", r"\textbackslash{}")
           .replace("&", r"\&").replace("%", r"\%").replace("$", r"\$")
           .replace("#", r"\#").replace("_", r"\_").replace("{", r"\{").replace("}", r"\}")
           .replace("~", r"\textasciitilde{}").replace("^", r"\textasciicircum{}"))
    for a, b in (("→", r"$\rightarrow$"), ("—", "--"), ("–", "--"), ("±", r"$\pm$"),
                 ("Δ", r"$\Delta$"), ("α", r"$\alpha$"), ("≈", r"$\approx$"),
                 ("✅", r"\checkmark"), ("❌", r"$\times$"), ("≥", r"$\geq$"), ("≤", r"$\leq$")):
        s = s.replace(a, b)
    return s


def f(x, nd=3):
    return "--" if x is None else (f"{x:.{nd}f}" if isinstance(x, float) else str(x))


def table(stem, caption, label, colspec, header, rows, note=None, size="\\scriptsize"):
    # E5b tables ALWAYS carry the URR disambiguation note (single source: e5b_metric_note.py)
    note = (note + " " + NOTE_TEX) if note else NOTE_TEX
    t = ["% Auto-generated by generate_paper_tables.py from executed artifacts. Do not edit by hand.",
         "% Requires: \\usepackage{booktabs}",
         "\\begin{table*}[!t]", "\\centering", size,
         f"\\caption{{{caption}}}", f"\\label{{{label}}}",
         f"\\begin{{tabular}}{{{colspec}}}", "\\toprule",
         " & ".join(header) + " \\\\", "\\midrule"]
    for r in rows:
        t.append(" & ".join(str(c) for c in r) + " \\\\")
    t += ["\\bottomrule", "\\end{tabular}"]
    if note:
        t.append(f"\\\\[2pt]\n\\begin{{minipage}}{{\\textwidth}}\\footnotesize {note}\\end{{minipage}}")
    t += ["\\end{table*}", ""]
    OUT.mkdir(exist_ok=True)
    (OUT / f"{stem}.tex").write_text("\n".join(t))
    return OUT / f"{stem}.tex"


# --------------------------------------------------------------------------- Table 1
def table_combined_ablation(ca):
    rows = []
    for c in ca["configs"]:
        rows.append([esc(c["config"]), esc("+".join(c["disabled_codes"]) or "--"),
                     f(c["blind_decision_accuracy"]), f(c["undetected_risk_rate"]),
                     f(c["benign_flag_rate"]), f(c["blind_risk_detection_recall"]),
                     f(c["evidence_completeness"]), f(c["ledger_integrity"]),
                     f(c["hash_chain_integrity"]), f(c["replay_integrity"]),
                     f(c["latency_mean_ms"], 4), f(c["runtime_integrity_score"]),
                     esc(c["overall_runtime_verdict"].split(" (")[0])])
    return table(
        "table_combined_ablation",
        "Combined component ablation of the L-DREA runtime. Each configuration executes the full "
        "runtime; every value is measured. RIS is the Runtime Integrity Score (mean of six health "
        "planes, normalised so the intact stack scores 1.000). A dash denotes a metric that cannot "
        "exist under that configuration (e.g. ledger integrity with the ledger removed).",
        "tab:combined-ablation", "llrrrrrrrrrrl",
        ["Configuration", "Disabled", "BlindAcc", "URR", "BFR", "Recall", "Evid.", "Ledger",
         "HashChain", "Replay", "Lat.\\,(ms)", "RIS", "Verdict"],
        rows,
        note=f"$n={ca['workload_n']}$ decisions per configuration; baseline RIS "
             f"$={f(ca['baseline_runtime_integrity_score'])}$. Components: "
             f"PE~=~predicate engine, RV~=~runtime revocation, EQ~=~evidence quad, "
             f"LG~=~runtime ledger, HC~=~hash chain.")


# --------------------------------------------------------------------------- Table 2
def table_statistics(st):
    """Per-configuration statistics for the headline metrics: point estimate, interval, effect size,
    p-value, significance. Uses the CORRECT test per metric kind (Cohen's h for proportions,
    Cohen's d for the latency distribution)."""
    rows = []
    for cname, blk in st["configs"].items():
        if cname == "baseline_full_LDREA":
            continue
        fpr = blk.get("undetected_risk_rate", {})
        rec = blk.get("blind_risk_detection_recall", {})
        lat = blk.get("latency_ms", {})
        ris = blk.get("runtime_integrity_score", {})
        fw = fpr.get("wilson95") or {}
        ld = lat.get("descriptive") or {}
        lb = lat.get("bootstrap95") or {}
        rd = ris.get("descriptive") or {}
        rows.append([
            esc(cname),
            f((fpr.get("descriptive") or {}).get("mean")),
            f"[{f(fw.get('low'))}, {f(fw.get('high'))}]" if fw else "--",
            f((fpr.get("cohens_h") or {}).get("h")),
            f((rec.get("descriptive") or {}).get("mean")),
            f((rec.get("cohens_h") or {}).get("h")),
            f(ld.get("mean"), 4),
            f"[{f(lb.get('low'),4)}, {f(lb.get('high'),4)}]" if lb else "--",
            f((lat.get("cohens_d") or {}).get("d"), 2),
            f(rd.get("mean")),
            "$<$0.001" if (fpr.get("p_value") is not None and fpr["p_value"] < 0.001)
            else f(fpr.get("p_value"), 3),
            r"\checkmark" if fpr.get("significant") else "--",
        ])
    return table(
        "table_statistics",
        "Statistical analysis of each ablated configuration against the full-stack baseline. "
        "Proportions use Wilson intervals and Cohen's $h$ (the correct effect size for a difference "
        "of rates); the latency distribution uses a percentile bootstrap interval and Cohen's $d$. "
        "Significance is the two-proportion $z$-test on the undetected-risk rate (URR) at $\\alpha=0.05$.",
        "tab:statistics", "lrcrrrrcrrrc",
        ["Configuration", "URR", "Wilson 95\\% CI", "$h$", "Recall", "$h$",
         "Lat.\\,(ms)", "Bootstrap 95\\% CI", "$d$", "RIS", "$p$", "Sig."],
        rows,
        note=f"$\\alpha=0.05$; {st.get('n_bootstrap')} bootstrap replicates (seed "
             f"{st.get('bootstrap_seed')}). Full per-metric statistics for all "
             f"{len(st['configs'])} configurations (17 metrics each), including Cliff's $\\delta$ and "
             f"Mann--Whitney $U$, are in \\texttt{{combined\\_statistics.json}}. Metrics that cannot "
             f"exist under a configuration carry an explicit \\texttt{{undefined\\_reason}} rather "
             f"than being silently dropped.")


# --------------------------------------------------------------------------- Table 3
def table_interactions(ca):
    rows = []
    for it in ca["interactions"]:
        rows.append([esc(it["combination"]), it["order"],
                     f(it["additive_prediction"]), f(it["observed_degradation"]),
                     f"{it['interaction_effect']:+.3f}",
                     esc(it["interaction_class"].split(" (")[0])])
    return table(
        "table_interactions",
        "Measured interaction effects between runtime components. The expected degradation is the "
        "sum of the two (or three) single-removal degradations; the observed degradation is measured "
        "by executing the combination. The interaction effect is their difference, and the "
        "classification follows from the measured values, not from an assumption.",
        "tab:interactions", "lrrrrl",
        ["Combination", "Order", "Expected $\\Delta$RIS", "Observed $\\Delta$RIS",
         "Interaction", "Classification"],
        rows,
        note="\\emph{Critical Dependency}: the upstream component is a prerequisite of the "
             "downstream one, so the downstream plane was already destroyed by the upstream removal "
             "alone and the combined effect equals the upstream single effect rather than the sum "
             "(the evidence~$\\rightarrow$~ledger~$\\rightarrow$~hash-chain cascade). "
             "\\emph{Additive}: the components act on independent planes. \\emph{Redundant "
             "(saturated)}: the additive prediction exceeds the total integrity of the stack, so the "
             "composite floors at zero. No combination measured as \\emph{Synergistic}.")


# --------------------------------------------------------------------------- Table 4
def table_threshold_sensitivity(ts):
    st = ts["stability"]
    rows = []
    for k, v in st["checks"].items():
        rows.append([esc(k.replace("_", " ")), yn(v["holds_at_every_scale"])])
    bs = st["baseline_sensitivity"]
    sens = []
    for s in ts["scales"]:
        sens.append([f"{int((s-1)*100):+d}\\%",
                     f(bs["undetected_risk_rate_by_scale"][str(s)]),
                     f(bs["risk_detection_by_scale"][str(s)])])
    # two stacked tabulars in one float
    t = ["% Auto-generated by generate_paper_tables.py. Requires \\usepackage{booktabs}",
         "\\begin{table}[!t]", "\\centering", "\\footnotesize",
         "\\caption{Threshold sensitivity. The unsupervised-calibrated operating point is perturbed "
         "by $\\pm10\\%$ and $\\pm20\\%$ and the runtime is re-executed. The baseline operating point "
         "moves, as expected; every ablation conclusion holds at every scale.}",
         "\\label{tab:threshold-sensitivity}",
         "\\begin{tabular}{lc}", "\\toprule",
         "Ablation conclusion & Holds at every scale \\\\", "\\midrule"]
    for r in rows:
        t.append(" & ".join(str(c) for c in r) + " \\\\")
    t += ["\\bottomrule", "\\end{tabular}", "\\\\[6pt]",
          "\\begin{tabular}{rrr}", "\\toprule",
          "Threshold & Baseline URR & Baseline Recall \\\\", "\\midrule"]
    for r in sens:
        t.append(" & ".join(str(c) for c in r) + " \\\\")
    perturbed = ", ".join(x.replace("_", chr(92) + "_") for x in ts["perturbed_thresholds"])
    stable = yn(st["all_conclusions_stable"])
    t += ["\\bottomrule", "\\end{tabular}",
          "\\\\[2pt]", "\\begin{minipage}{\\columnwidth}\\footnotesize "
          f"Perturbed: \\texttt{{{perturbed}}}. "
          f"{ts['n_executions']} executions. Conclusions stable: {stable}. "
          f"URR spread across $\\pm20\\%$: {f(bs['urr_spread'])}. "
          "The thresholds are unsupervised quantiles learned from the unlabelled warm-up prefix, not "
          "hand-chosen constants; the frozen $\\Gamma$ rule is untouched. " + NOTE_TEX +
          "\\end{minipage}",
          "\\end{table}", ""]
    OUT.mkdir(exist_ok=True)
    (OUT / "table_threshold_sensitivity.tex").write_text("\n".join(t))
    return OUT / "table_threshold_sensitivity.tex"


# --------------------------------------------------------------------------- Table 5
def table_cross_dataset(cd):
    rows = []
    for d in cd["datasets"]:
        by = {"+".join(c["disabled_codes"]) or "--": c for c in d["configs"]}
        base, pe, eq = by.get("--"), by.get("PE"), by.get("EQ")
        rows.append([
            esc(d["dataset"]), esc(d["domain"]), f"{d['rows_loaded']:,}",
            f"{d['prevalence']*100:.2f}\\%", str(d["n_predicates"]),
            f(base["blind_decision_accuracy"]), f(base["undetected_risk_rate"]),
            f(base["blind_risk_detection_recall"]), f(base["runtime_integrity_score"]),
            f(pe["undetected_risk_rate"]) if pe else "--",
            f(eq["evidence_completeness"]) if eq else "--",
        ])
    con = cd["cross_dataset_conclusions"]
    replicates = yn(con["all_conclusions_replicate"])
    return table(
        "table_cross_dataset",
        "The complete combined ablation executed independently on every real dataset. Datasets are "
        "not merged and metrics are not normalised across them: prevalence and the observable feature "
        "space differ by design, so the absolute rates are not comparable. What replicates is the "
        "ablation STRUCTURE.",
        "tab:cross-dataset", "llrrrrrrrrr",
        ["Dataset", "Domain", "Rows", "Prev.", "Preds",
         "BlindAcc", "URR", "Recall", "RIS", "URR (--PE)", "Evid. (--EQ)"],
        rows,
        note=("Columns 6--9 are the full-stack baseline on that dataset. The last two columns are the "
              "ablated results that carry the finding: removing the predicate engine (--PE) drives the "
              "undetected-risk rate (URR) to 1.000 on \\emph{every} dataset, and removing the evidence quad "
              "(--EQ) zeroes evidence completeness and cascades the ledger to undefined on every "
              "dataset. Ablating the audit plane (EQ/LG/HC) leaves the undetected-risk rate (URR) bit-identical "
              "to the baseline, confirming the ledger is strictly downstream of the authorisation "
              f"decision. Conclusions replicate on all datasets: {replicates}. "
              "$\\Gamma$ is imported and used identically for every dataset."))


def main() -> int:
    ca = L("experiments/combined_ablation/combined_ablation.json")
    st = L("experiments/combined_ablation/combined_statistics.json")
    ts = L("experiments/combined_ablation/threshold_sensitivity.json")
    cd = L("experiments/combined_ablation/cross_dataset_ablation.json")
    written, skipped = [], []
    if ca.get("configs"):
        written.append(table_combined_ablation(ca)); written.append(table_interactions(ca))
    else:
        skipped.append("table_combined_ablation.tex / table_interactions.tex (combined_ablation.json absent)")
    if st.get("configs"):
        written.append(table_statistics(st))
    else:
        skipped.append("table_statistics.tex (combined_statistics.json absent)")
    if ts.get("stability"):
        written.append(table_threshold_sensitivity(ts))
    else:
        skipped.append("table_threshold_sensitivity.tex (threshold_sensitivity.json absent)")
    if cd.get("datasets"):
        written.append(table_cross_dataset(cd))
    else:
        skipped.append("table_cross_dataset.tex (cross_dataset_ablation.json absent)")
    for p in written:
        print(f"[paper-tables] wrote {p.relative_to(ROOT)} ({p.stat().st_size:,} B)")
    for s in skipped:
        print(f"[paper-tables] SKIPPED {s}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
