sankey-beta

send_money,PERMIT,2
schedule_transaction,PERMIT,1
get_webpage,PERMIT,1
invite_user_to_slack,SAFE_STATE,1
post_webpage,PERMIT,2
post_webpage,SAFE_STATE,1
send_direct_message,PERMIT,1
add_user_to_channel,PERMIT,1
reserve_hotel,PERMIT,1
reschedule_calendar_event,PERMIT,2
add_calendar_event_participants,SAFE_STATE,1